# freeDiameter config for the HSS (S6a peer -> MME).
Identity = "hss.localdomain";
Realm = "localdomain";

ListenOn = "10.100.2.8";
NoRelay;

LoadExtension = "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dbg_msg_dumps.fdx" : "0x8888";
LoadExtension = "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_rfc5777.fdx";
LoadExtension = "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_mip6i.fdx";
LoadExtension = "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_nasreq.fdx";
LoadExtension = "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_nas_mipv6.fdx";
LoadExtension = "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_dcca.fdx";
LoadExtension = "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_dcca_3gpp.fdx";

TLS_Cred = "/open5gs/install/etc/open5gs/tls/hss.crt", "/open5gs/install/etc/open5gs/tls/hss.key";
TLS_CA = "/open5gs/install/etc/open5gs/tls/ca.crt";

ConnectPeer = "mme.localdomain" { ConnectTo = "10.100.2.10"; No_TLS; };
