# freeDiameter config for the SMF/PGW-C (Gx peer -> PCRF).
Identity = "smf.localdomain";
Realm = "localdomain";

ListenOn = "10.100.2.13";
NoRelay;

LoadExtension = "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dbg_msg_dumps.fdx" : "0x8888";
LoadExtension = "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_rfc5777.fdx";
LoadExtension = "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_mip6i.fdx";
LoadExtension = "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_nasreq.fdx";
LoadExtension = "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_nas_mipv6.fdx";
LoadExtension = "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_dcca.fdx";
LoadExtension = "/open5gs/install/lib/x86_64-linux-gnu/freeDiameter/dict_dcca_3gpp.fdx";

TLS_Cred = "/open5gs/install/etc/open5gs/tls/smf.crt", "/open5gs/install/etc/open5gs/tls/smf.key";
TLS_CA = "/open5gs/install/etc/open5gs/tls/ca.crt";

ConnectPeer = "pcrf.localdomain" { ConnectTo = "10.100.2.9"; No_TLS; };
